[database_admin]
host = "localhost"
user = "root"
password = "password"
database = "pfb_coches"
port = 3306

[database_user]
host = "localhost"
user = "grupocds"
password = "JoSanBross"
database = "pfb_coches"
port = 3306
